[versions]
crashlytics = "2.9.9"
firebase-analytics-ktx = "21.3.0"
firebase-crashlytics-ktx = "18.4.3"
google-services = "4.4.0"
gradle = "8.1.1"
kotlin-gradle-plugin = "1.8.0"
ktx = "1.10.1"
appcompat = "1.6.1"
constraint = "2.1.4"
leakcanary = "2.12"
lifecycle = "2.6.2"
fragment = "1.6.1"
material = "1.9.0"
vb-delegate = "1.5.2"
glide = "4.12.0"
gson = "2.9.0"
retrofit = "2.9.0"
retrofit2-coroutines = "0.9.2"
koin = "3.1.3"
room = "2.5.2"
reflect = "1.8.10"
coroutines = "1.7.3"
cicerone = "7.1"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraint = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint" }
androidx-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }

crashlytics = { module = "com.google.firebase:crashlytics", version.ref = "crashlytics" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebase-analytics-ktx" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebase-crashlytics-ktx" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }

gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }

leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
viewbinding-delegate = { group = "com.github.kirich1409", name = "viewbindingpropertydelegate-noreflection", version.ref = "vb-delegate" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
retrofit2-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit2-coroutines = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlin-coroutines-adapter", version.ref = "retrofit2-coroutines" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }

room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-common = { group = "androidx.room", name = "room-common", version.ref = "room" }

kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "reflect" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

cicerone = { group = "com.github.terrakok", name = "cicerone", version.ref = "cicerone" }
